In [35]:
import numpy as np
x=np.array([[1,2,3],[2,3,5]])
#print("x",formet(x))
print("x:\n{}".format(x))

x:
[[1 2 3]
 [2 3 5]]


In [30]:
from scipy import sparse
y=np.eye(4)
print("y:\n{}".format(y))

y:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
sparse_matrix=sparse.csr_matrix(y)
print("Sparse  matrix y:\n{}".format(sparse_matrix))

Sparse  matrix y:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [32]:
import numpy as np
x=np.array([[1,2,3],[2,3,5]])
sparse_matrix=sparse.csr_matrix(x)
print("Sparse  matrix x:\n{}".format(sparse_matrix))

Sparse  matrix x:
  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	2
  (1, 1)	3
  (1, 2)	5


In [46]:
data=np.ones(5)
row_indices=np.arange(5)
column_indices=np.arange(5)
sparse_new_matrix=sparse.coo_matrix(data,(row_indices,row_indices))
print("Coo matirx data:\n{}".format(sparse_new_matrix))

Coo matirx data:
  (0, 0)	1.0
  (0, 1)	1.0
  (0, 2)	1.0
  (0, 3)	1.0
  (0, 4)	1.0
